name: Dependency Checks

on:
  workflow_call:

jobs:
  node-dependency-checks:
    name: node modules checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '24'

      - name: Dependency Check
        run: npm audit --audit-level=high
