name: CI

on:
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yaml

  security:
    name: Security Analysis
    uses: ./.github/workflows/codeql-security-analysis.yaml
    secrets: inherit
    permissions:
      contents: read
      security-events: write
      packages: read

  dependency-checks:
    name: Dependency Checks
    uses: ./.github/workflows/dependency-checks.yaml

  docker:
    needs: [test, security, dependency-checks]
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
